"""Structured retrieval priors generated by affect."""

from __future__ import annotations

from affect.emotion_profile import EmotionProfile

NEGATIVE_EMOTIONS = {"sadness", "sad", "fear", "anger", "disgust", "disgust_loathing", "boredom"}


def generate_retrieval_priors(
    profile: EmotionProfile,
    salience: float,
    volatility: float,
) -> dict[str, float]:
    negative_intensity = sum(score for emotion, score in profile.emotions.items() if emotion in NEGATIVE_EMOTIONS)
    return {
        "boost_emotional_memories": round(min(1.0, salience), 6),
        "boost_recent_memories": round(min(1.0, 0.25 + volatility * 0.6), 6),
        "boost_negative_experiences": round(min(1.0, negative_intensity), 6),
        "boost_stabilizing_memories": round(min(1.0, max(0.0, -profile.valence) * 0.5), 6),
    }
